name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubunto-latest
    strategy:
      matrix:
        node-versions: [ 17.x ]

    steps:
      - uses: action/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install module
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting ts
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:css

